export const GET_LIST_BLOG = "GET_LIST_BLOG";
export const GET_LIST_BLOG_START = "GET_LIST_BLOG_START";
export const GET_LIST_BLOG_SUCCESS = "GET_LIST_BLOG_SUCCESS";
export const GET_LIST_BLOG_FAILED = "GET_LIST_BLOG_FAILED";
